# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('cod_prov', models.IntegerField(db_column='COD_PROV', primary_key=True, serialize=False)),
                ('razon_social', models.CharField(blank=True, db_column='RAZON_SOCIAL', max_length=100, null=True)),
                ('ruc', models.CharField(blank=True, db_column='RUC', max_length=11, null=True, unique=True)),
            ],
            options={
                'db_table': 'PROVEEDORES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorStock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cod_rpov', models.IntegerField()),
                ('razon_social', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=11)),
            ],
        ),
    ]
