# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='nro_asientos',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
